info:
    description: Instagram Unfollow

server:
  port: 4269

spring:
  main:
    web-application-type: none
    allow-circular-references: true
  jpa:
    show-sql: true
    database-platform: com.nero.socialmedia.analysis.instagram.configuration.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
  sql:
    init:
      mode: always

settings:
  googleDriveFilepath:
    fieldName: google-drive-filepath
    multiple: false
  instagramAccountsToTrack:
    fieldName: instagram-accounts-to-track
    multiple: true

ui:
  stage:
    title: Instagram Analyze
  tray:
    openMenuItemLabel: Open
    exitMenuItemLabel: Exit
    tooltip: Running instagram analyze application

